- README.md
A simple plugin for customizing which items are dropped upon death.
> Add CustomMediumcore

- README.md
> Added FACommands and TerraJump

- README.md
> Add Terracord

- README.md
Add Character Reset by Bippity (updated to 1.4 w/ latest TShockAPI support and Void Vault)
Custom Items is currently broken so no point in keeping a defective plugin on here until Johuan or myself manages to fix it.
Also added a Community Maintained Plugin header and moved my stuff to there.
> Add Character Reset and remove Custom Items

- README.md
This pull request adds the following plugins to the list:
- [TDiffBackup](https://github.com/tieonlinux/TDiffBackup)
- [ShortCommands](https://github.com/tieonlinux/ShortCommands)
Note: Both repos use github actions to build, test and release a plugin dll.
> Add 2 plugins to the list

- README.md
Updated old plugin from https://github.com/Jewsus/AutoTeamPlus
> Added Auto Team

- README.md
Tested on **TShock 4.4.0 Pre 15**
Originally Came from here: ' https://tshock.co/xf/index.php?resources/buff-emotions.128/ '
But was outdated and got updated towards this version now.
> Add Buff Emoticons

- README.md
Admittedly this is in somewhat of a proof-of-concept stage at the moment, but I intend to build it out with more metrics and hope that submitting it here could lead to more eyes on it to get suggestions for interesting metrics to add.
First proposed [here](https://github.com/Pryaxis/TShock/discussions/2196)
> Add TShockPrometheus

- README.md
due to popular request...i think?
decided to update infinite chests myself bc it's such an easy change to make it work
> Updated CharacterReset + InfiniteChestsV3 + Ghost + NPCBlocker + AutoRegister

- README.md
fixes https://github.com/Adventure-Terraria-Server-Project/AdditionalPylons-Plugin/issues/1
> Update AdditionalPylons plugin to 1.1.0.0

- README.md
Contact via Discord: Lady Narnia#7777
> Plugin submission for TerrariaChatRelay

- README.md
Feels a bit mean to add it to the top of the list, but that's what previous commits have done.
Perhaps alphabetically order plugins in the future?
Tested on Mono running under Linux, _not_ tested on Windows -- I say this out of fear of possible `System.Drawing` weirdness.
> Add WorldMapper to README.md

- README.md
Provides `/lplg`, for listing currently loaded plugins
> Submission for ListPluginsPlugin

- README.md
Some people are having issues deciding which version of crossplay that should be downloaded. This commit tries to fix that
> Fix readability issues

- README.md
Simple IRC chat bridge, I tried to keep the codebase to a minimum size.
> Add IRCrarria

- README.md
Save data when players are transferred to other servers, so that player data can be synchronized when multiple servers share the same database.
> Update to 1.5.2

- README.md
It was updated with this change: https://github.com/ZakFahey/SmartRegions/commit/8bf51be867f0d24b18b153fc124dbcb777aa44b6
> Update Smart Regions

- README.md
> Replacing NameVal > ChatManager & Adding WorldEdit

- README.md
Self explanatory. I hope putting it at the top is fine.
> Add AutoTeam

- README.md
Recently I have changed my username. Thanks!
> Update username to Metacinnabar

- README.md
Adds support for Terraria Servers running 1.4.3
> Update Crossplay to v1.5.0

- README.md
Add protocol compatibility with (future) servers running v1.4.3.1
> Update Crossplay to 1.6.0

- README.md
A repository for collecting Chinese plugins
> Add TShock Chinese Plugin Collection

- README.md
[TShock Chinese Plugin Collection](https://github.com/UnrealMultiple/TShockPlugin) repository has been moved to an organization
> Update `TShock Chinese Plugin Collection` repository url

- README.md
Please let me know if any changes are needed!
> Update TerrariaChatRelay in readme
